# Default values for namespace.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: default

labels: {}
annotations: {}

commonLabels: {}
commonAnnotations: {}

limitRange:
  enabled: false
  limits: {}
  # limits:
  # - type: Container
  # - type: Pod
  # - type: PersistentVolumeClaim
  #   min:
  #     storage: 100Mi
  #   max:
  #     storage: 100Gi

resourceQuotas: []
# resourceQuota:
# - name: object-count-quota
#   hard:
#     count/pods: 0
#   scopeSelector:
#     matchExpressions:
#     - operator: In
#       scopeName: PriorityClass
#       values:
#       - system-node-critical
#       - system-cluster-critical
